version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "events-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-yr8bqe8f8juc"
s3_prefix = "events-app"
region = "us-west-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
